### ISSUE TITLE
"[ReflectionException]  Class HpsServicesConfig does not exist" on compile

### ISSUE THREAD

**Issue by markalston** [hps/heartland-magento2-module#1]
When running  php bin/magento setup:di:compile the following error is thrown:
 [ReflectionException]
  Class HpsServicesConfig does not exist

Area configuration aggregation stops at 5/7 [====================>-------]  71% 2 mins 186.0 MiB0 MiB

The setup for secure submit is there in the admin page and I can add the keys properly.

However when going to the cart or checkout pages after trying to install this module magento fails with:
Invalid block type: Magento\Checkout\Block\Onepage 
and
Invalid block type: Magento\Checkout\Block\Cart\Shipping

Looks like the failed compilation borks the whole system.

This is with Magento ver. 2.0.7

**Comment by ttnnkkrr** [comment]
Thank you for reporting this. Are you on a windows machine using something like WAMP or XAMP?

Are you on a Linux device? Which Distro?
What user are you running commands as? is it the same user that runs your httpd\apache2 instance.

### Verify Permissions:

You may also want to verify that your directory permissions are correct 
The permissions requirements recently changed. It is possible that this prevented your installation from setting up the SDK dependencies for this module
[new file-system-perms as of 2.07](http://devdocs.magento.com/guides/v2.0/install-gde/prereq/file-system-perms.html) Below would be one approach to fixing this assuming a Linux based system
`cd <your Magento install dir>`
`find var vendor pub/static pub/media app/etc -type f -exec chmod g+w {} \;`
`find var vendor pub/static pub/media app/etc -type d -exec chmod g+w {} \;`
`chmod u+x bin/magento`

### To manually add the dependencies

`composer require hps/heartland-php` to ensure the missing class is included.

Please get back to me with your OS and what server your using (APACHE, nginx) and your PHP version
In the mean while I will download your version and see if i can replicate the issue.

Any detail that you're willing to share on what steps you executed leading to this error can be helpful

**Comment by ttnnkkrr** [comment]
Markalston, Did you get it working, Can you tell me about your OS. Does vendor/hps/heartland-php exist?

**Comment by ttnnkkrr** [comment]
Can you provide the steps necessary to reproduce your issue? 

I have built a fresh Ubuntu 14.02 with Apache/2.4.7 and PHP 5.6.22-1+donate.sury.org~trusty+1 and MySQL 5.6.30-0ubuntu0.14.04.1. When following the latest Magento2 installation procedure and then following the exact module installation instructions from the readme page, I had no errors. 
My installation beyond the base image for Ubuntu.
I am providing a vagrant file to reproduce my system. [Vagrantfile.zip](https://github.com/hps/heartland-magento2-module/files/295531/Vagrantfile.zip)
Along with the commands below you should be able to duplicate success and perhaps identify what may be the difference. 

```
sudo apt-get install -y mysql-server-5.6

sudo apt-add-repository ppa:ondrej/php5-5.6
sudo apt-get -y update

apt-get install -y apache2 php5 php5-mhash php5-mcrypt php5-curl php5-cli php5-mysql php5-gd php5-intl php5-xsl curl git locate

sudo curl -sS https://getcomposer.org/installer | php
sudo cp composer.phar /usr/local/bin/composer
sudo chmod +x /usr/local/bin/composer
```

Magento2 Installation instructions i used
http://devdocs.magento.com/guides/v2.0/install-gde/prereq/integrator_install.html

```
composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition <installation directory name>
```

"installation directory name" needs to be an empty or even non existent directory
 Once that completes and it could take a while, Below is an example of the command line i used. Substitute your own values

```
magento setup:install --base-url="YOUR URL" --db-host=DBHOST_IP_FQDN --db-name=magento2 --db-user=root --db-password=secret --admin-firstname=adminFirstName --admin-lastname=adminLastName --admin-email="yourEmail@Somedomain.com" --admin-user=adminUser --admin-password="SuperSecretPass" --language=en_US --currency="USD" --timezone="America/Chicago" --use-rewrites=1
```

**Comment by markalston** [comment]
Sorry for the delay.  I have been squashing some other issues with 
magento (working around the marketplace not syncing in 2.0.7).  I will 
backup and run these tests this afternoon.

**Comment by ttnnkkrr** [comment]
Understood

**Comment by ttnnkkrr** [comment]
I managed to duplicate this issue finally last night by executing the installation as root. Magento2 has some rather finicky permissions policies implemented. You can execute as a user with sudo privileges that is a member of the web service group. Apache group is often www-data. 

```
cd <your Magento install dir>
chown -R nonRootUsermemberof-www-data:www-data .
```

The Apache web service must be in a group with write access set by the commands above.

```
cd <your Magento install dir>
find var vendor pub/static pub/media app/etc -type f -exec chmod g+w {} \;
find var vendor pub/static pub/media app/etc -type d -exec chmod g+w {} \;
chmod u+x bin/magento
```

**Comment by ttnnkkrr** [comment]
@markalston Have you gotten this resolved is there anything further i can help with?
I attempted to send you an email on your developer account with my direct contact information as well.

**Comment by markalston** [comment]
On 06/07/2016 09:05 AM, Charlie Simmons wrote:

> @markalston https://github.com/markalston Have you gotten this 
> resolved is there anything further i can help with?
> I attempted to send you an email on your developer account with my 
> direct contact information as well.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub 
> https://github.com/hps/heartland-magento2-module/issues/1#issuecomment-224310187, 
> or mute the thread 
> https://github.com/notifications/unsubscribe/AM4hycLiSWXntkxqvb0zFO8bux6Wi4tuks5qJYjFgaJpZM4IoClk.
> 
> I sincerely appreciate the work.  I have been so busy dealing with other 
> magento 2 issues that I still haven't gotten to it.  I have a new 
> develop site built and will give it another test shortly.  I am pretty 
> confident that it was a combo of the permissions issue and the missing 
> dependency.  I have hit that dependency issue on several other occasions 
> this week and finally added all those commands into a shell script to 
> make fixing them quick and easy.

Give me another day or so and I'll get back to you.

**Comment by ttnnkkrr** [comment]
No problem. My only concern was that you might need something else and weren't getting it.

**Comment by markalston** [comment]
Fixed! It was the command: composer require hps/heartland-php which did 
the trick.  Was that supposed to be automatic when running magento 
setup:upgrade?   As I am running php 7.0.6 perhaps there is some 
difference there. Anyway, that seems to have fixed it.

Thanks,
Mark Alston

**Comment by ttnnkkrr** [comment]
Thanks i will check it out with that version and see
Thanks I will close this issue
