### ISSUE TITLE
Update module to work with 2.1.3

### ISSUE THREAD

**Issue by mhodge13** [hps/heartland-magento2-module#19]
The Heartland module does not seem to be updated to work with the latest release of Magento 2.1.3.  The one issue that I see currently is that Magento changed the display of the payment methods in the admin panel showing 3 sections now (Recommended Solutions, Other PayPal Payment Solutions, Other Payment Methods).

The current module has the system.xml group set as sortOrder of "1.9" which gets overridden when the "other_payment_methods" group is output since it has a sortOrder of "4".  This means that the Heartland Module should be updated to show in the Other Payment Methods section by updating the sortOrder to be "10" if the payment method is to be shown before the others since "Zero Subtotal Checkout" has a sortOrder of 30.

This is only for display purposes in the admin payment methods section.

**Comment by ttnnkkrr** [comment]
Thank you for reporting this I will update accordingly

**Comment by ttnnkkrr** [comment]
please check the develop branch this should be resolved

**Comment by mhodge13** [comment]
This seems correct in the etc/adminhtml/system.xml file.

Thanks for the quick turnaround.
