### ISSUE TITLE
url developer.heartlandpaymentsystems.com timeout

### ISSUE THREAD

**Issue by refaelgold** [hps/heartland-magento2-module#2]
This site can’t be reached

developer.heartlandpaymentsystems.com took too long to respond.

**Comment by slogsdon** [comment]
@refaelgold Are you currently located outside of the United States? If so, please send us an email at EntApp_DevPortal@e-hps.com, and we can get this sorted out for you.

**Comment by refaelgold** [comment]
cool,i will

**Comment by ttnnkkrr** [comment]
@refaelgold Did you ever get this resolved ?
