### ISSUE TITLE
Class HpsServicesConfig does not exist

### ISSUE THREAD

**Issue by cristinaLogic** [hps/heartland-magento2-module#24]
Hy,
I'm trying to install this module on a magento store but when i'm running php bin/magento setup:di:compile it give's me that "Class HpsServicesConfig does not exist". 
Where can i find this class?
...PS: I haven't installed all the requirements

**Comment by ttnnkkrr** [comment]
@cristinaLogic Did you resolve this issue?

**Comment by cristinaLogic** [comment]
Yes @ttnnkkrr, i resolved it. I've forgotten to Install Dependencies with composer require hps/heartland-php
