### ISSUE TITLE
Error creating Credit Memo in Magento 2.3.4

### ISSUE THREAD

**Issue by awg-cconway** [hps/heartland-magento2-module#50]
We are getting the following error when we load the credit memo screen in Magento 2.3.4:

main.CRITICAL: Type Error occurred when creating object: Magento\Sales\ViewModel\CreditMemo\Create\UpdateTotalsButton [] []

Has anyone had the same issue or have a fix for this?

**Comment by slogsdon** [comment]
Hi @cconway24! I haven't seen this one before, but it seems specific to Magento internals.

**Comment by awg-cconway** [comment]
@slogsdon yea looks to be a Magento bug, it affects 2 of our other sites as well. Thank you!

**Comment by slogsdon** [comment]
Closing this, but feel free to reopen if there's a need. Thanks!
